#!/bin/sh
#Part of cobuntu-config-gui (Link)
#
# See LICENSE file for copyright and license details

#
#설치 함수
#

do_docky_install() {
	apt-get install docky
	apt-get update
}

do_docky_configuration() {

}

do_numix_install() {
	apt-get install numix
	apt-get update
}

do_numix_circle_icon_install() {
	apt-add-repository ppa:numix/ppa
	apt-get update
	apt-get install numix-icon-theme numix-icon-theme-circle

do_compiz_install() {
	apt-get install compiz compizconfig-settings-manager compiz-fusion-plugins-extra compiz-fusion-plugins-main compiz-plugins
}

do_compiz_configuration() {

}

do_cairo_dock_install() {
	add-apt-repository ppa:cairo-dock-team/ppa
	apt-get update
	apt-get install cairo-dock cairo-dock-plug-ins

do_cairo_dock_configuration() {

}

do_concky_install() {
	apt-get install conky-all
}

do_concky_start() {
	conky &
}




