#!/bin/sh
#Part of cobuntu-config-gui (Link)
#
# See LICENSE file for copyright and license details

INTERACTIVE=True
ASK_TO_REBOOT=0
EXEC_PATH=/usr/bin/
IM_SWITCH_KEY='<Shift>space'
IM_SWITCH_KEY_BACK='<Shift><Super>space'
USEFUL_APPS='vim git' # 유용한 앱들은 여기에 추가
VERSION='0.1.3'

argc=$#
argv0=$0
argv1=$1

argcv()
{
    if [ $argc -gt 0 ];
    then
        if [ "$argv1" == "-h" -o "$argv1" == "--help" ];
        then
            echo -e "-h, --help\t도움말을 보여줍니다."
            echo -e "-v, --version\t버전 정보를 보여줍니다."
        fi
        if [ "$argv1" == "-v" -o "$argv1" == "--version" ];
        then
            echo $VERSION
        fi

        exit 0
    fi
}

#
#설치 함수
#

do_docky_install() {
	apt-get install docky
	apt-get update
}


do_docky_configuration() {

}

do_numix_install() {
	apt-get install numix
	apt-get update
}

do_numix_circle_icon_install() {
	apt-add-repository ppa:numix/ppa
	apt-get update
	apt-get install numix-icon-theme numix-icon-theme-circle

do_compiz_install() {
	apt-get install compiz compizconfig-settings-manager compiz-fusion-plugins-extra compiz-fusion-plugins-main compiz-plugins
}

do_compiz_configuration() {

}

do_cairo_dock_install() {
	add-apt-repository ppa:cairo-dock-team/ppa
	apt-get update
	apt-get install cairo-dock cairo-dock-plug-ins

do_cairo_dock_configuration() {

}

do_concky_install() {
	apt-get install conky-all
}

do_concky_start() {
	conky &
}





